### ISSUE TITLE
We need more memes

### ISSUE THREAD

**Issue by elmartirta** [BesHackers/QHacks2018#2]
P r o n t o

**Comment by omocube** [comment]
^ y e e t e d. 

send them to the Memery Bank.

**Comment by elmartirta** [comment]
Agreed.

- Sent from my iPhone

**Comment by omocube** [comment]
^ fourthed.

- Sent from my Pipboy 3000

**Comment by omocube** [comment]
<img width="506" alt="screen shot 2017-10-16 at 11 05 18 pm" src="https://user-images.githubusercontent.com/36054891/35707167-b8f94c44-0776-11e8-825c-9e1b5c5cee79.png">

A proposed solution. 

- Sent from my Easy Bake Oven

**Comment by elmartirta** [comment]
Memes have been delivered.
